### ISSUE TITLE
Missing URLs

### ISSUE THREAD

**Issue by FolfyBlue** [Revadike/InternalSteamWebAPI#2]
Hey, this file: https://github.com/autarc/steam-store/blob/master/lib/api/steam.js
contains a bunch of URLs that are not listed such as:
/api/getappsincategory/
/api/getappsingenre/
/api/addtocart/
and much more. The file also tells you the proper arguments to use

**Comment by Revadike** [comment]
Yes, it's far from complete, but feel free to contribute yourself.

**Comment by Revadike** [comment]
I've listed all endpoints on https://github.com/Revadike/InternalSteamWebAPI/wiki
I will generate pages for them later.
Again, I encourage you to help! <3

**Comment by Revadike** [comment]
I've generated the pages!
https://github.com/Revadike/InternalSteamWebAPI/wiki
