### ISSUE TITLE
Get-Market-Price-History not work now

### ISSUE THREAD

**Issue by maxwebgt** [Revadike/InternalSteamWebAPI#3]
https://github.com/Revadike/InternalSteamWebAPI/wiki/Get-Market-Price-History
i am very sad. but it's not working now. And i dont find a true endpoint.

**Comment by woctezuma** [comment]
I have just tested with the example provided on the Wiki page, and I cannot reproduce your issue.

**Comment by maxwebgt** [comment]
> I have just tested with the example provided on the Wiki page, and I cannot reproduce your issue.

https://steamcommunity.com/market/pricehistory/?appid=753&market_hash_name=228280-Xan
what is your server response for this request? I have an empty array 
![image](https://user-images.githubusercontent.com/17952062/133596760-df7cdf2e-1e7f-4554-82f0-51a579b773c6.png)

**Comment by woctezuma** [comment]
![Response](https://i.ibb.co/FW4rzXX/2021-09-16-12-44-15.png)

**Comment by maxwebgt** [comment]
all other queries are working fine, but this one is not working. I have no idea why this could be. Maybe I'm missing something?

**Comment by maxwebgt** [comment]
to get information on this request, I need to be authorized on steam site. Sorry. Thx.

**Comment by Revadike** [comment]
Well, glad you figured it out.
Thanks, nevertheless, I'll put `Authenticated: Yes` on the wiki page.
